import { Inter } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import "./globals.css";
import { Button } from "@/components/ui/button";
import Notifications from "@/components/Notifications";
import APIKeyManager from "@/components/APIKeyManager";
import { Metadata } from "next";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Droog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header className="w-full h-[3rem] flex justify-between items-center p-5 bg-gradient-to-r from-[#2e1348] to-[#a855f7] text-white">
            <Link href="/">
              <h1 className="text-2xl font-bold">DROOG</h1>
            </Link>
            
            <div className="flex items-center space-x-4">
              <Notifications />
              <APIKeyManager />

              <SignedOut>
                <SignInButton mode="modal">
                  <Button variant="secondary">Sign In</Button>
                </SignInButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
